SET IDENTITY_INSERT dbo.Quote ON
GO

MERGE INTO dbo.Quote AS TARGET
USING (VALUES ( 1, 'steven-wright',      'Support bacteria – they’re the only culture some people have.'),
              ( 2, 'steven-wright',      'What happens if you get scared half to death twice?'),
              ( 3, 'steven-wright',      'What’s another word for Thesaurus?'),
              ( 4, 'steven-wright',      'When everything is coming your way, you’re in the wrong lane.'),
              ( 5, 'steven-wright',      'I went to the hardware store and bought some used paint. It was in the shape of a house. I also bought some batteries, but they weren’t included.'),
              ( 6, 'steven-wright',      'I woke up one morning, and all of my stuff had been stolen and replaced by exact duplicates.'),
              ( 7, 'steven-wright',      'I worked in a health food store once. A guy came in and asked me, “If I melt dry ice, can I take a bath without getting wet?”'),
              ( 8, 'steven-wright',      'If you think nobody cares about you, try missing a couple of payments'),
              ( 9, 'steven-wright',      'If you were going to shoot a mime, would you use a silencer?'),
              (10, 'steven-wright',      'I went to a fancy French restaurant called “Deja Vu.” The headwaiter said, “Don’t I know you?”'),
              (11, 'steven-wright',      'I went to a general store. They wouldn’t let me buy anything specifically.'),
              (12, 'steven-wright',      'The hardness of the butter is proportional to the softness of the bread.'),
              (13, 'steven-wright',      'I went to a restaurant that serves “breakfast at any time”. So I ordered French Toast during the Renaissance.'),
              (14, 'steven-wright',      'I went to the bank and asked to borrow a cup of money. They said, “What for?” I said, “I’m going to buy some sugar.”'),
              (15, 'steven-wright',      'If you write the word “monkey” a million times, do you start to think you’re Shakespeare?'),
              (16, 'steven-wright',      'In my house on the ceilings I have paintings of the rooms above…so I never have to go upstairs.'),
              (17, 'steven-wright',      'It’s a small world, but I wouldn’t want to have to paint it.'),
              (18, 'steven-wright',      'Join the Army, meet interesting people, kill them.'),
              (19, 'steven-wright',      'Many people quit looking for work when they find a job.'),
              (20, 'steven-wright',      'Monday is an awful way to spend 1/7th of your life.'),
              (21, 'steven-wright',      'My socks DO match. They’re the same thickness.'),
              (22, 'steven-wright',      'Officer, I know I was going faster than 55MPH, but I wasn’t going to be on the road an hour.'),
              (23, 'steven-wright',      'The judge asked, “What do you plead?” I said, “Insanity, your honor, who in their right mind would park in the passing lane?”'),
              (24, 'steven-wright',      'OK, so what’s the speed of dark?'),
              (25, 'steven-wright',      'On the other hand, you have different fingers.'),
              (26, 'steven-wright',      'One night I walked home very late and fell asleep in somebody’s satellite dish. My dreams were showing up on TV’s all over the world.'),
              (27, 'steven-wright',      'I wrote a song, but I can’t read music so I don’t know what it is. Every once in a while I’ll be listening to the radio and I say, “I think I might have written that.”'),
              (28, 'steven-wright',      'I’d kill for a Nobel Peace Prize.'),
              (29, 'steven-wright',      'If at first you don’t succeed, then skydiving definitely isn’t for you.'),
              (30, 'steven-wright',      'If everything seems to be going well, you have obviously overlooked something.'),
              (31, 'steven-wright',      'One time a cop pulled me over for running a stop sign. He said, “Didn’t you see the stop sign?” I said, “Yeah, but I don’t believe everything I read.”'),
              (32, 'steven-wright',      'Plan to be spontaneous tomorrow.'),
              (33, 'steven-wright',      'Right now I’m having amnesia and deja vu at the same time.'),
              (34, 'steven-wright',      'The problem with the gene pool is that there is no lifeguard.'),
              (35, 'steven-wright',      'Someone sent me a postcard picture of the earth. On the back it said, “Wish you were here.”'),
              (36, 'steven-wright',      'Sponges grow in the ocean. That just kills me. I wonder how much deeper the ocean would be if that didn’t happen.'),
              (37, 'george-carlin',      'The reason I talk to myself is because I’m the only one whose answers I accept.'),
              (38, 'george-carlin',      'Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?'),
              (39, 'george-carlin',      'May the forces of evil become confused on the way to your house.'),
              (40, 'george-carlin',      'Never underestimate the power of stupid people in large groups.'),
              (41, 'george-carlin',      'If you try to fail, and succeed, which have you done?'),
              (42, 'george-carlin',      'The main reason Santa is so jolly is because he knows where all the bad girls live.'),
              (43, 'george-carlin',      'I went to a bookstore and asked the saleswoman, ''Where''s the self-help section?'' She said if she told me, it would defeat the purpose.'),
              (44, 'bob-newhart',        'I don''t like country music, but I don''t mean to denigrate those who do. And for the people who like country music, denigrate means ''put down''.'),
              (45, 'steven-wright',      'The severity of the itch is proportional to the reach.'),
              (46, 'bob-newhart',        'The only way to survive is to have a sense of humor.'),
              (47, 'bernie-mac',         'You can''t change what happened, just like you can''t change the future by worrying about it.  You just have to keep moving.'),
              (48, 'bernie-mac',         'I can''t build myself by beating somebody down.'),
              (49, 'redd-foxx',          'Beauty may be skin dep, but ugly goes cleer to the bone.'),
              (50, 'redd-foxx',          'If you can see the handwriting on the wall... you''re on the toilet.'),
              (51, 'rodney-dangerfield', 'My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you''re ugly too.'),
              (52, 'rodney-dangerfield', 'I tell ya, I knew my morning wasn''t going right. When I put on my shirt the button fell off, when I picked up my briefcase, the handle fell off, I tell ya, I was afraid to go to the bathroom.'),
              (53, 'rodney-dangerfield', 'I told my wife a man is like wine, he gets better with age. She locked me in the cellar.'),
              (54, 'rodney-dangerfield', 'I told my psychiatrist that everyone hates me. He said I was being ridiculous - everyone hasn''t met me yet.'),
              (55, 'rodney-dangerfield', 'Look out for number one and try not to step in number two.'),
              (56, 'steven-wright',      'The sooner you fall behind, the more time you’ll have to catch up.'),
              (57, 'bill-burr',          'Surround yourself with positive people. Also, be a positive person. Root for people. Somebody else''s success is not your failure.'),
              (58, 'steve-martin',       'Before you criticize a man, walk a mile in his shoes. That way, when you do criticize him, you''ll be a mile away and have his shoes.'),
              (59, 'steve-martin',       'I thought yesterday was the first day of the rest of my life but it turns out today is.'),
              (60, 'steve-martin',       'Be so good they can''t ignore you.'),
              (61, 'steve-martin',       'I believe in equality. Equality for everybody. No matter how stupid they are or how superior I am to them.'),
              (62, 'steve-martin',       'A father carries pictures where his money used to be.'),
              (63, 'steve-martin',       'I just downloaded eleven hundred books onto my Kindle, and now I can’t lift it.'),
              (64, 'steve-martin',       'First the doctor told me the good news: I was going to have a disease named after me.'),
              (65, 'robin-williams',     'Why do they call it "rush hour" when nothing moves?'),
              (66, 'joel-spolsky',       'It''s harder to read code than to write it.'),
              (68, 'steven-wright',       'To steal ideas from one person is plagiarism; to steal from many is research.'),
              (69, 'alan-turing',        'Programming is a skill best acquired by practice and example rather than from books.'),
              (70, 'linus-torvalds',     'Most good programmers do programming not because they expectt to get paid or get adulation by the public, but because it is fun to program.'),
              (71, 'dolly-parton',       'If you don’t like the road you’re walking, start paving another one.'),
              (72, 'steven-wright',      'Today I dialed a wrong number… The other person said, “Hello?” and I said, “Hello, could I speak to Joey?”… They said, “Uh… I don’t think so…he’s only 2 months old.” I said, “I’ll wait.”'),
              (73, 'steven-wright',      'What a nice night for an evening.'))
AS SOURCE (QuoteId,
           AuthorId,
           Content)
ON TARGET.QuoteId = SOURCE.QuoteId
WHEN MATCHED THEN UPDATE SET TARGET.AuthorId = SOURCE.AuthorId,
                             TARGET.Content  = SOURCE.Content
WHEN NOT MATCHED THEN INSERT (QuoteId,
                              AuthorId,
                              Content)
                      VALUES (SOURCE.QuoteId,
                              SOURCE.AuthorId,
                              SOURCE.Content);
GO

SET IDENTITY_INSERT dbo.Quote OFF
GO